export const syncContract = {
  version: 2,
  direction: "Vlacky -> iTrain",
  purpose: "Collection definitions and current speed-profile backup. No hardware control or decoder programming.",
  speedProfiles: "Vlacky stores only the latest speed profile per physical locomotive, normally imported from iTrain. referenceOnly.speedProfile is a backup, never an automatically applied source field. Preserve both saved directions even for a single-direction measurement. Restore requires a separate explicit request, verified physical identity/configuration and a tested version-specific adapter preserving all other calibration/layout data. No restore or iTrain importer is implemented by this read-only server.",
  identity: "Match sourceId using a persisted mapping scoped to the iTrain project. Never match solely by designation or DCC address. Ambiguous matches require resolution.",
  updates: "Patch only explicitly mapped fields on existing iTrain objects. Never recreate/replace a locomotive or regenerate a whole project to update collection data. Preserve existing iTrain object IDs and references.",
  allowedSourceFields: ["designation", "operator", "modelManufacturer", "catalogNumber", "classType", "notes", "image", "dccAddress", "decoders.address", "decoders.functions", "trains.composition"],
  alwaysPreserveInITrain: [
    "Measured forward and reverse speed profiles and speed-step measurements",
    "Speed calibration, profiling results and measurement history",
    "Braking, stopping, acceleration/deceleration calibration and correction factors",
    "Detector offsets, feedback assignments and layout-specific vehicle settings",
    "Blocks, routes, reservations, current positions and live operating state",
    "All target fields not explicitly allowed by the verified version-specific field mapping",
  ],
  missingValues: "null/missing means unknown: preserve the target value. An empty function list is not a request to delete existing iTrain functions.",
  deletions: "Absence from an export is not a deletion request. Never delete iTrain objects automatically.",
  decoderFunctions: "Merge mapped function definitions by decoder identity and F number. Preserve other functions and unknown properties. Sound/light/other are broad categories, not iTrain function-type identifiers. Report unsupported decoder arrangements or functions instead of guessing.",
  referenceOnly: ["Current speed-profile backup", "CV records", "sound project names", "manual URLs", "train route/era descriptions"],
  cvPolicy: "Never apply CV records to hardware or use them to replace measured speed profiles. These are notes, not an executable programming recipe.",
  trainPolicy: "Compositions are saved collection definitions. Do not assign locations, activate trains, reserve routes or assume compositions sharing a physical vehicle can operate simultaneously. Orientation is unknown unless explicitly recorded; preserve target orientation.",
  templates: "Sample/template vehicles are excluded by default. Never synchronize them unless explicitly requested. Trains containing excluded vehicles are omitted in full and reported; never export a silently incomplete composition.",
  images: "Download with bearer authentication, verify SHA-256, and store in a persistent local image folder. PNG is offered for compatibility. Never put an API token or temporary URL into iTrain image settings.",
  procedure: [
    "Read get_sync_contract and retrieve the current collection snapshot.",
    "Resolve source IDs to existing iTrain objects using the project-specific mapping.",
    "Prepare a field-by-field diff for the requested vehicles/trains; flag unsupported changes.",
    "Before any file write: ensure iTrain has saved and closed the target project, back it up and check that its hash still matches the file used for the diff.",
    "Apply only the explicitly mapped fields with a tested adapter for the installed iTrain version; preserve unknown XML, existing IDs and unrelated archive resources.",
    "Assert that all calibration/profile data and unrelated settings are unchanged; abort if this cannot be proven. Repeating the same sync must produce no further changes.",
    "Validate the result in iTrain offline and report applied, unchanged, skipped and conflicting fields.",
  ],
  enforcement: "This server is read-only and cannot modify iTrain. These rules are a mandatory integration contract; a local updater must enforce and test them. Server instructions alone cannot prevent arbitrary external XML edits.",
} as const;
export const mcpInstructions = "Vlacky is the source of collection definitions. Always read get_sync_contract before iTrain work. NEVER overwrite measured forward/reverse speed profiles, speed-step data, braking/stopping calibration, detector offsets, or layout settings. Patch only verified mapped fields; never replace/recreate existing locomotive objects. CVs are reference notes, not programming commands. Samples are excluded by default. Use stable source IDs and download images with authentication. " + syncContract.enforcement;
